### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MarcoCusinato** [MarcoCusinato/AeViz#3]
- [x] Add a better derivation of the shock radius in 3D
- [x] Complete $h_+$ and $h_x$ derivation in 3D from the spherical harmonics
- [ ] Add documentation
- [x] Add advanced plotting
